# Generated by Django 5.1.6 on 2025-03-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='reader_borrowed_books',
            field=models.CharField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_borrower_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
