# Generated by Django 5.1.6 on 2025-03-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0002_reader_reader_borrowed_books_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowed_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(blank=True, max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='reader',
            name='reader_borrowed_books',
        ),
    ]
