# Generated by Django 5.1.6 on 2025-03-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_borrowed_history_remove_reader_reader_borrowed_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='reader_password',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
