# Generated by Django 5.1.6 on 2025-03-06 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0004_reader_reader_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_stock_number',
            field=models.IntegerField(default=1),
        ),
    ]
